<a href="https://colab.research.google.com/github/JonasHagstrom79/Tensorflow/blob/main/00_Introduction_to_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.8.0


### Load a dataset

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 0s 0us/step


### Build machine learning model
Build a tf.keras.Sequential model by stacking layers.

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation="relu"),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
#For each example, the model returns a vector of logits or log-odds scores, one for each class.
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.09146693,  0.40485698, -0.4776778 ,  0.24456692, -0.13669503,
        -0.02615167, -0.19972104,  0.5054159 , -0.47619057,  0.03156859]],
      dtype=float32)

In [5]:
#For each example, the model returns a vector of logits or log-odds scores, one for each class.
tf.nn.softmax(predictions).numpy()

array([[0.10467474, 0.14320081, 0.05924688, 0.12199229, 0.08332061,
        0.09305952, 0.0782313 , 0.15834986, 0.05933506, 0.09858898]],
      dtype=float32)

In [6]:
#Define a loss function for training using losses.SparseCategoricalCrossentropy, 
#which takes a vector of logits and a True index and returns a scalar loss for each example.

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
#This loss is equal to the negative log probability of the true class: The loss
#is zero if the model is sure of the correct class. This untrained model gives 
#probabilities close to random (1/10 for each class), so the initial loss should
# be close to -tf.math.log(1/10) ~= 2.3.

loss_fn(y_train[:1], predictions).numpy()

2.374516

In [8]:
#Before you start training, configure and compile the model using Keras Model.compile. 
#Set the optimizer class to adam, set the loss to the loss_fn function you defined 
#earlier, and specify a metric to be evaluated for the model by setting the metrics 
#parameter to accuracy.

model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


###Train and evaluate your model

In [9]:
#Use the Model.fit method to adjust your model parameters and minimize the loss:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2933 - accuracy: 0.9148
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1436 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1086 - accuracy: 0.9666
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0914 - accuracy: 0.9712
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0760 - accuracy: 0.9764


In [10]:
#The Model.evaluate method checks the models performance, usually on a "Validation-set" or "Test-set".

model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0740 - accuracy: 0.9768 - 543ms/epoch - 2ms/step


[0.07396453619003296, 0.9768000245094299]

In [12]:
#The image classifier is now trained to ~98% accuracy on this dataset. To learn more, 
#read the TensorFlow tutorials. If you want your model to return a probability, 
#you can wrap the trained model, and attach the softmax to it:

probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.56315581e-08, 8.97627785e-08, 1.34627815e-04, 1.45397280e-04,
        4.46852888e-10, 3.68354989e-07, 1.78219527e-12, 9.99715626e-01,
        1.82660233e-06, 1.94049562e-06],
       [6.12708746e-08, 4.00152581e-04, 9.99596179e-01, 3.22874234e-06,
        1.45229635e-16, 5.15991871e-08, 1.00588494e-07, 5.19636959e-13,
        8.46668584e-08, 9.99073879e-16],
       [3.45782269e-07, 9.98516262e-01, 5.42096386e-04, 4.03714876e-05,
        6.40410217e-05, 1.61219668e-05, 1.81916148e-05, 6.36558281e-04,
        1.63684424e-04, 2.36594224e-06],
       [9.99897718e-01, 6.95624625e-09, 1.67599665e-05, 1.01776365e-07,
        1.58448501e-07, 2.84057342e-06, 3.88368471e-06, 5.48922217e-05,
        7.68314266e-08, 2.36840351e-05],
       [2.56335261e-06, 2.51153237e-10, 8.82391134e-07, 3.61841273e-07,
        9.98928249e-01, 5.23063513e-08, 1.74852312e-06, 4.35270085e-05,
        6.34460685e-06, 1.01618713e-03]], dtype=float32)>