In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.device_count)

2.9.0+cpu
False
<function device_count at 0x7a217ce7b7e0>


In [2]:
# scalar
scalr = torch.tensor(7)
scalr

tensor(7)

In [3]:
scalr.ndim

0

In [4]:
# Get tensor back as Python int
scalr.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6 ]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape # One three by three bracket

torch.Size([1, 3, 3])

### Random tensors

Random tensors are important because the way many neural networks learn is that
they start with tensors full of random numbers and then adjust those numbers to better represent the data.


In [16]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3142, 0.3452, 0.3218, 0.0073],
        [0.2829, 0.9510, 0.4794, 0.3396],
        [0.1123, 0.3571, 0.7844, 0.4321]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [19]:
# Create a tensoe of all zeros
zero = torch.zeros(size=(3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensor-like

In [21]:
# Use torch.range()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
torch.arange(start=0, end=1000, step=42)

tensor([  0,  42,  84, 126, 168, 210, 252, 294, 336, 378, 420, 462, 504, 546,
        588, 630, 672, 714, 756, 798, 840, 882, 924, 966])

In [23]:
# Creating tensors like
one_to_ten = torch.arange(1, 11,1)
one_to_ten
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not the right datatype
2. Tensors not the right shape
3. Tensors not on the right device

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, # datatype
                               device=None, # CPU/GPU
                               requires_grad=False # Wheter or not to track gradients with this tensors operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor


tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors

1. Tensors not the right datatype - to get datatype from a tensor, use `tensor.dtype`
2. Tensors not the right shape - to get shape from a tensor, use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, use `tensor.device`

In [28]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8311, 0.0365, 0.9673, 0.0816],
        [0.9980, 0.8389, 0.8869, 0.3344],
        [0.5417, 0.2430, 0.7973, 0.4678]])

In [29]:
# Find out detalis about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.8311, 0.0365, 0.9673, 0.0816],
        [0.9980, 0.8389, 0.8869, 0.3344],
        [0.5417, 0.2430, 0.7973, 0.4678]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [30]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [31]:
# Multiply tensor by 10
tensor *10

tensor([10, 20, 30])

In [32]:
# Subtract 10
tensor -10

tensor([-9, -8, -7])

In [33]:
# Try out PyTorch in-build functions
torch.mul(tensor, 10)
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)


In [34]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [35]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [36]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [37]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.19 ms, sys: 20 µs, total: 2.21 ms
Wall time: 4.02 ms


In [38]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 73 µs, sys: 0 ns, total: 73 µs
Wall time: 83.9 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [49]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [50]:
print(tensor_A.shape, tensor_B.shape)

torch.Size([3, 2]) torch.Size([3, 2])


In [47]:
tensor_A.shape

AttributeError: 'builtin_function_or_method' object has no attribute 'shape'

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.


In [54]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [56]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [57]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [66]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [67]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [68]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [69]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [70]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positinal min and max

In [71]:
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [72]:
x.argmin()

tensor(0)

In [73]:
x[0]

tensor(1)

In [74]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [75]:
x[9]

tensor(91)

from types import WrapperDescriptorType
## Reshaping, stcking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shaped
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimension from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted ( swapped) in a certain way


In [76]:
# Create tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [79]:
# Ad an extra dimension
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [81]:
# Change the view
z = x.view(3, 3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [82]:
# Changing z changes x (because a view of a tensor shares the same memory as the original impput)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [83]:
# Stack tensors on top each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [84]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])