<a href="https://colab.research.google.com/github/JonasHagstrom79/Tensorflow/blob/main/00_TensorFlow_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 🛠 00. TensorFlow Fundamentals Exercises



1.   Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2.   Find the shape, rank and size of the tensors you created in 1.
3.  Create two tensors containing random values between 0 and 1 with shape [5, 300]. 
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.





In [5]:
import tensorflow as tf


### 1

In [6]:
scalar = tf.constant(10) #Scalar: a single number
vector = tf.constant([10,10]) #Vector: a number with direction (e.g wind speed and direction)
matrix = tf.constant(([10, 10],
                      [9, 9])) #Matrix: a 2-dimensional array of numbers
tensor = tf.constant([[[1,2,3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
scalar, vector, matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 10],
        [ 9,  9]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int32)>)

###2

In [7]:
scalar.shape

TensorShape([])

In [8]:
vector.shape

TensorShape([2])

In [9]:
matrix.shape

TensorShape([2, 2])

In [10]:
tensor.shape

TensorShape([3, 2, 3])

In [12]:
tf.rank(scalar)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [13]:
tf.rank(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [14]:
tf.rank(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [15]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [16]:
tf.size(scalar)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [17]:
tf.size(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [18]:
tf.size(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [19]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=18>

###3