<a href="https://colab.research.google.com/github/JonasHagstrom79/Tensorflow/blob/main/00_TensorFlow_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 🛠 00. TensorFlow Fundamentals Exercises



1.   Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2.   Find the shape, rank and size of the tensors you created in 1.
3.  Create two tensors containing random values between 0 and 1 with shape [5, 300]. 
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.





In [32]:
import tensorflow as tf


### 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [33]:
scalar = tf.constant(10) #Scalar: a single number
vector = tf.constant([10,10]) #Vector: a number with direction (e.g wind speed and direction)
matrix = tf.constant(([10, 10],
                      [9, 9])) #Matrix: a 2-dimensional array of numbers
tensor = tf.constant([[[1,2,3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
scalar, vector, matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 10],
        [ 9,  9]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int32)>)

###2. Find the shape, rank and size of the tensors you created in 1.

In [34]:
scalar.shape

TensorShape([])

In [35]:
vector.shape

TensorShape([2])

In [36]:
matrix.shape

TensorShape([2, 2])

In [37]:
tensor.shape

TensorShape([3, 2, 3])

In [38]:
tf.rank(scalar)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [39]:
tf.rank(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [40]:
tf.rank(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [41]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [42]:
tf.size(scalar)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [43]:
tf.size(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [44]:
tf.size(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [45]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=18>

###3. Create two tensors containing random values between 0 and 1 with shape [5, 300]. 

In [79]:
#randomOne = tf.random.uniform([5, 300], minval=0, maxval=1)
#randomOne
import numpy as np
X = tf.constant(np.random.randint(0, 2, size=[5, 300]))
X

<tf.Tensor: shape=(5, 300), dtype=int64, numpy=
array([[1, 1, 1, ..., 0, 0, 1],
       [1, 0, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [1, 1, 1, ..., 0, 0, 1],
       [1, 1, 0, ..., 0, 1, 1]])>

In [86]:
#randomTwo = tf.random.uniform([5, 300], minval=0, maxval=1)
#randomTwo
Y = tf.constant(np.random.randint(0, 2, size=[5, 300]))
Y

<tf.Tensor: shape=(5, 300), dtype=int64, numpy=
array([[0, 0, 1, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 1, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 0, 1]])>

### 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [89]:
#tf.size(randomOne)
#tf.print(randomOne, randomTwo)
tf.linalg.matmul(tf.transpose(X), Y)
#randomOne @ randomTwo
#tf.matmul(randomOne, tf.transpose(randomTwo)) #became a 5,5 tensor

<tf.Tensor: shape=(300, 300), dtype=int64, numpy=
array([[1, 1, 3, ..., 4, 3, 2],
       [1, 1, 3, ..., 3, 2, 2],
       [1, 0, 2, ..., 3, 3, 1],
       ...,
       [0, 0, 0, ..., 1, 1, 0],
       [0, 1, 1, ..., 2, 1, 1],
       [2, 1, 4, ..., 4, 3, 2]])>

### 5. Multiply the two tensors you created in 3 using dot product.

In [87]:
#tf.tensordot(tf.transpose(randomOne), randomTwo, axes=1) #became a 300, 300 tensor
tf.tensordot(tf.transpose(X), Y, axes=1) #became a 300, 300 tensor

<tf.Tensor: shape=(300, 300), dtype=int64, numpy=
array([[1, 1, 3, ..., 4, 3, 2],
       [1, 1, 3, ..., 3, 2, 2],
       [1, 0, 2, ..., 3, 3, 1],
       ...,
       [0, 0, 0, ..., 1, 1, 0],
       [0, 1, 1, ..., 2, 1, 1],
       [2, 1, 4, ..., 4, 3, 2]])>

### 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [92]:
#randomThree = tf.random.uniform([224,224, 3], minval=0, maxval=1)
#randomThree
Z = tf.constant(np.random.randint(0, 2, size=[224, 224, 3]))
Z

<tf.Tensor: shape=(224, 224, 3), dtype=int64, numpy=
array([[[0, 0, 0],
        [1, 0, 0],
        [1, 0, 0],
        ...,
        [0, 1, 1],
        [1, 0, 1],
        [1, 1, 1]],

       [[0, 0, 0],
        [1, 0, 0],
        [0, 0, 0],
        ...,
        [1, 0, 0],
        [0, 1, 1],
        [1, 1, 0]],

       [[1, 1, 1],
        [0, 1, 1],
        [1, 0, 1],
        ...,
        [1, 1, 1],
        [0, 0, 1],
        [0, 1, 0]],

       ...,

       [[0, 1, 0],
        [0, 0, 0],
        [1, 0, 1],
        ...,
        [0, 0, 1],
        [1, 0, 1],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 0, 0],
        [1, 0, 1],
        ...,
        [1, 0, 0],
        [1, 1, 0],
        [0, 1, 1]],

       [[0, 0, 1],
        [1, 0, 0],
        [0, 1, 1],
        ...,
        [0, 0, 1],
        [0, 0, 0],
        [1, 1, 0]]])>

### 7. Find the min and max values of the tensor you created in 6 along the first axis

In [108]:
tf.reduce_min(Z, axis=0)

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]

In [111]:
tf.reduce_max(Z, axis=0)

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]

### 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [113]:
Å = tf.constant(np.random.randint(0, 30, size=[1,224, 224, 3]))
Å

<tf.Tensor: shape=(1, 224, 224, 3), dtype=int64, numpy=
array([[[[25,  1,  4],
         [13, 26, 25],
         [28, 24, 28],
         ...,
         [ 9, 16, 26],
         [ 7,  5, 16],
         [ 2, 14, 12]],

        [[13, 13,  4],
         [ 9,  8, 14],
         [17, 24, 25],
         ...,
         [17,  4, 28],
         [20, 21, 20],
         [23, 18, 23]],

        [[ 1, 24,  6],
         [ 8, 22,  0],
         [23,  0, 15],
         ...,
         [18, 13, 27],
         [ 0, 21, 12],
         [ 3, 24, 26]],

        ...,

        [[29,  7,  3],
         [24,  1, 16],
         [14, 25,  7],
         ...,
         [ 3, 27, 14],
         [ 7, 23, 27],
         [16,  0, 17]],

        [[20,  0,  1],
         [ 9, 19, 25],
         [10, 18,  0],
         ...,
         [23, 12, 28],
         [18,  8,  8],
         [ 6, 14, 14]],

        [[ 7,  2, 18],
         [18, 26, 19],
         [ 6, 22,  9],
         ...,
         [ 3,  5,  8],
         [22, 14, 27],
         [23, 29, 18]]]])>

In [116]:
Å_squeezed = tf.squeeze(Å)
Å_squeezed, Å_squeezed.shape

(<tf.Tensor: shape=(224, 224, 3), dtype=int64, numpy=
 array([[[25,  1,  4],
         [13, 26, 25],
         [28, 24, 28],
         ...,
         [ 9, 16, 26],
         [ 7,  5, 16],
         [ 2, 14, 12]],
 
        [[13, 13,  4],
         [ 9,  8, 14],
         [17, 24, 25],
         ...,
         [17,  4, 28],
         [20, 21, 20],
         [23, 18, 23]],
 
        [[ 1, 24,  6],
         [ 8, 22,  0],
         [23,  0, 15],
         ...,
         [18, 13, 27],
         [ 0, 21, 12],
         [ 3, 24, 26]],
 
        ...,
 
        [[29,  7,  3],
         [24,  1, 16],
         [14, 25,  7],
         ...,
         [ 3, 27, 14],
         [ 7, 23, 27],
         [16,  0, 17]],
 
        [[20,  0,  1],
         [ 9, 19, 25],
         [10, 18,  0],
         ...,
         [23, 12, 28],
         [18,  8,  8],
         [ 6, 14, 14]],
 
        [[ 7,  2, 18],
         [18, 26, 19],
         [ 6, 22,  9],
         ...,
         [ 3,  5,  8],
         [22, 14, 27],
         [23, 29, 18]]])>, 

### 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [123]:
Ä = tf.constant(np.random.randint(0, 42, size=[10]))
Ä
#Ä[tf.argmax(Ä)]

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([22,  7, 21, 15, 25, 30, 35, 39, 40, 15])>

In [135]:
tf.argmax(Ä)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

### 10. One-hot encode the tensor you created in 9

In [136]:
tf.one_hot(Ä, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>